version: '3.3'

services:
   mongodb:
      container_name: mongodb
      image: mongo
      restart: always
      ports:
         - 27017:27017
      volumes:
         - mongodb-volume:/data/db
   mariadb:
      container_name: mariadb
      image: mariadb
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: techday
         MYSQL_USER: user 
         MYSQL_PASSWORD: pass
      ports:
         - 3306:3306
      volumes:
         - mariadb-volume:/var/lib/mysql
   postgresql:
      container_name: postgresql
      image: postgres
      restart: always
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: pass
         POSTGRES_DB: techday
      ports:
         - 5432:5432
      volumes:
         - postgresql-volume:/var/lib/postgresql
   rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:management
      hostname: rabbitmq
      restart: always
      ports:
         - 5672:5672
         - 15672:15672
      volumes:
         - rabbitmq-volume:/var/lib/rabbitmq/mnesia
   msjava:
      container_name: msjava
      image: manuexcd/msjava
      environment:
         SPRING_PROFILES_ACTIVE: docker
         MICROSERVICES_MSKOTLIN_URL: http://mskotlin:8081/mskotlin
      ports:
         - 8080:8080
      labels: 
         kompose.service.type: loadbalancer
   mskotlin:
      container_name: mskotlin
      image: manuexcd/mskotlin
      environment:
         SPRING_PROFILES_ACTIVE: docker
      ports:
         - 8081:8081
      labels: 
         kompose.service.type: loadbalancer
   msjavaconsumer:
      container_name: msjavaconsumer
      image: manuexcd/msjavaconsumer
      environment:
         SPRING_PROFILES_ACTIVE: docker
      ports:
         - 8082:8082
      labels: 
         kompose.service.type: loadbalancer
volumes:
   mongodb-volume:
   mariadb-volume:
   postgresql-volume:
   rabbitmq-volume: