apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql-deployment
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: techday
        - name: POSTGRES_PASSWORD
          value: pass
        - name: POSTGRES_USER
          value: user
        image: postgres:10.4
        name: postgresql
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresql-volume
      restartPolicy: Always
      volumes:
      - name: postgresql-volume
        persistentVolumeClaim:
          claimName: postgresql-volume