apiVersion: v1
kind: Service
metadata:
  labels:
    app: {label}
  name: {serviceName}
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    app: {label}
  type: {servicetype}