apiVersion: v1
kind: Service
metadata:
  labels:
    app: {label}
  name: {serviceName}
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: {label}
  type: {serviceType}