apiVersion: v1
kind: Service
metadata:
  labels:
    app: {label}
  name: {serviceName}
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: {label}
  type: {serviceType}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {label}
  name: {deploymentName}
spec:
  selector:
    matchLabels:
      app: {label}
  replicas: 1
  template:
    metadata:
      labels:
        app: {label}
    spec:
      containers:
      - env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://{serviceName}:27017/techday
        image: manuexcd/mskotlin
        name: mskotlin
        ports:
        - containerPort: 8081
      restartPolicy: Always