apiVersion: v1
kind: Service
metadata:
  labels:
    app: {label}
  name: {serviceName}
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: {label}
  type: {serviceType}