apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {label}
  name: {deploymentName}
spec:
  selector:
    matchLabels:
      app: {label}
  replicas: 1
  template:
    metadata:
      labels:
        app: {label}
    spec:
      containers:
      - env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://{serviceName}:27017/techday
        image: manuexcd/mskotlin
        name: mskotlin
        ports:
        - containerPort: 8081
      restartPolicy: Always