apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {label}
  name: {name}
spec:
  selector:
    matchLabels:
      app: {selector}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {label}
    spec:
      containers:
      - image: rabbitmq:management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name: {volumeName}
      hostname: rabbitmq
      restartPolicy: Always
      volumes:
      - name: {volumeName}
        persistentVolumeClaim:
          claimName: {claimName}