apiVersion: v1
kind: Service
metadata:
  labels:
    app: {label}
  name: {serviceName}
spec:
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    app: {selector}
  type: {serviceType}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {label}
  name: {name}
spec:
  selector:
    matchLabels:
      app: {selector}
  replicas: 1
  serviceName: {name}
  template:
    metadata:
      labels:
        app: {label}
    spec:
      containers:
      - image: rabbitmq:management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name: {volumeName}
      hostname: rabbitmq
      restartPolicy: Always
      volumes:
      - name: {volumeName}
        persistentVolumeClaim:
          claimName: {claimName}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {label}
  name: {claimName}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi