apiVersion: v1
kind: Service
metadata:
  labels:
    app: msjava
  name: msjava-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: msjava
  type: LoadBalancer