apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: msjava
  name: msjava-deployment
spec:
  selector:
    matchLabels:
      app: msjava
  replicas: 1
  template:
    metadata:
      labels:
        app: msjava
    spec:
      containers:
      - env:
        - name: MICROSERVICES_MSKOTLIN_URL
          value: http://mskotlin-service:8081/mskotlin
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mariadb-service:3306/techday
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq-service
        image: manuexcd/msjava
        name: msjava
        ports:
          - containerPort: 8080
      restartPolicy: Always