apiVersion: v1
kind: Service
metadata:
  labels:
    app: mskotlin
  name: mskotlin-service
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: mskotlin
  type: LoadBalancer